### ISSUE TITLE
Error with the Rviz 

### ISSUE THREAD

**Issue by Baldins** [Unity-Technologies/Robotics-Nav2-SLAM-Example#41]
Hi, I am getting errors where running ros2 launch unity_slam_example unity_slam_example.py in the terminal.

How can I fix it?

Thank you!

**Comment by ChengysTHU** [comment]
Maybe we have same problem?  And here is my logs when I try to start RViz in docker:

```bash
rosdev@0bef63e0e548:~$ ros2 launch unity_slam_example unity_slam_example.py
[INFO] [launch]: All log files can be found below /home/rosdev/.ros/log/2021-12-17-19-34-54-288833-0bef63e0e548-485
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py:226> exception=InvalidLaunchFileError('py')>
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/packages.py", line 50, in get_package_prefix
    content, package_prefix = get_resource('packages', package_name)
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/resources.py", line 48, in get_resource
    raise LookupError(
LookupError: Could not find the resource 'ros_tcp_endpoint' of type 'packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 68, in get_launch_description_from_python_launch_file
    return getattr(launch_file_module, 'generate_launch_description')()
  File "/home/rosdev/colcon_ws/install/unity_slam_example/share/unity_slam_example/unity_slam_example.py", line 16, in generate_launch_description
    os.path.join(get_package_share_directory('ros_tcp_endpoint'), 'launch', 'endpoint.py')
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/packages.py", line 70, in get_package_share_directory
    return os.path.join(get_package_prefix(package_name), 'share', package_name)
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/packages.py", line 52, in get_package_prefix
    raise PackageNotFoundError(
ament_index_python.packages.PackageNotFoundError: "package 'ros_tcp_endpoint' not found, searching: ['/home/rosdev/colcon_ws/install/unity_slam_example', '/opt/ros/galactic']"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 127, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [py]: "package 'ros_tcp_endpoint' not found, searching: ['/home/rosdev/colcon_ws/install/unity_slam_example', '/opt/ros/galactic']"

```

**Comment by Baldins** [comment]
Yes, I do have exactly the same problem !
________________________________

**Comment by mrpropellers** [comment]
Hi @Baldins, please refer to the [Troubleshooting section](https://github.com/Unity-Technologies/Robotics-Nav2-SLAM-Example/blob/main/readmes/run_example.md#Troubleshooting) where you can find your error. You likely did not check out the submodules and need to do a `git submodule update --init --recursive` and then rebuild the container.

**Comment by Baldins** [comment]
I did that already

On Dec 20, 2021, at 11:47 AM, Devin Miller (Unity) ***@***.***> wrote:

﻿

Hi @Baldins<https://github.com/Baldins>, please refer to the Troubleshooting section<https://github.com/Unity-Technologies/Robotics-Nav2-SLAM-Example/blob/main/readmes/run_example.md#Troubleshooting> where you can find your error. You likely did not check out the submodules and need to do a git submodule update --init --recursive and then rebuild the container.

**Comment by mrpropellers** [comment]
Could you double-check that you've completed all the steps listed, and that you don't have any stale containers open?  This error only shows up when the ros_tcp_endpoint package is missing from the colcon ws, which only happens when the package was not checked out locally before the container is built and run. Try navigating into the ros_tcp_endpoint directory to confirm that [these files ](https://github.com/Unity-Technologies/ROS-TCP-Endpoint/tree/09d97b2c95018099e3d2a8d8f1e8b168c895cdc9) exist locally before you build.

**Comment by Baldins** [comment]
Yes I did all the steps mentioned there - and I am using the docker.
I followed exactly all the steps as described but still have the same error

On Dec 20, 2021, at 4:00 PM, Devin Miller (Unity) ***@***.***> wrote:

﻿

Could you double-check that you've completed all the steps listed, and that you don't have any stale containers open? This error only shows up when the ros_tcp_endpoint package is missing from the colcon ws, which only happens when the package was not checked out locally before the container is built and run. Try navigating into the ros_tcp_endpoint directory to confirm that these files <https://github.com/Unity-Technologies/ROS-TCP-Endpoint/tree/09d97b2c95018099e3d2a8d8f1e8b168c895cdc9> exist locally before you build.

**Comment by mrpropellers** [comment]
@Baldins, please navigate to your colcon_ws/src/ros_tcp_endpoint directory inside the docker container and confirm that there are files in that directory.

**Comment by nowhereman1999** [comment]
> @Baldins, please navigate to your colcon_ws/src/ros_tcp_endpoint directory inside the docker container and confirm that there are files in that directory.

Hi,sorry to bother you,but I encountered with a similar error like this:
![image](https://user-images.githubusercontent.com/53631206/208689716-12aa16b4-ebaa-4f8a-9b23-68fcaf8183ef.png)
as you can see,I was absence of the nav2_bringup package,However,I have checked the ros_tcp_endpoint directory locally and there does have [those files](https://github.com/Unity-Technologies/ROS-TCP-Endpoint/tree/09d97b2c95018099e3d2a8d8f1e8b168c895cdc9)：
![image](https://user-images.githubusercontent.com/53631206/208690851-3a6b7eee-9404-46c2-a8d9-71e82fd27d87.png)
Besides,I also check it inside the docker container and it still have the files:
![image](https://user-images.githubusercontent.com/53631206/208691251-ea505a6c-22b0-45f4-8d2e-8281137522b5.png)
So what is the cause of this and how can I fix it, I hope you can give me some advice, I will be very grateful！

**Comment by wrxsky** [comment]
> > @Baldins, please navigate to your colcon_ws/src/ros_tcp_endpoint directory inside the docker container and confirm that there are files in that directory.
> 
> Hi,sorry to bother you,but I encountered with a similar error like this: ![image](https://user-images.githubusercontent.com/53631206/208689716-12aa16b4-ebaa-4f8a-9b23-68fcaf8183ef.png) as you can see,I was absence of the nav2_bringup package,However,I have checked the ros_tcp_endpoint directory locally and there does have [those files](https://github.com/Unity-Technologies/ROS-TCP-Endpoint/tree/09d97b2c95018099e3d2a8d8f1e8b168c895cdc9)： ![image](https://user-images.githubusercontent.com/53631206/208690851-3a6b7eee-9404-46c2-a8d9-71e82fd27d87.png) Besides,I also check it inside the docker container and it still have the files: ![image](https://user-images.githubusercontent.com/53631206/208691251-ea505a6c-22b0-45f4-8d2e-8281137522b5.png) So what is the cause of this and how can I fix it, I hope you can give me some advice, I will be very grateful！

Same with you. Still looking for a solution.

**Comment by ccwang65** [comment]
> @Baldins, please navigate to your colcon_ws/src/ros_tcp_endpoint directory inside the docker container and confirm that there are files in that directory.

I have similar error. Yes, the src directory has all the files, the error message seems indidating that it looks file from other directory: colcon_ws/install/unity_slam_example

**Comment by ccwang65** [comment]
For me, the package that is not found is 'nav2_bringup'. Any idea? Thanks.

Here is the entire output:

rosdev@f83d9cb31544:~$ ros2 launch unity_slam_example unity_slam_example.py
[INFO] [launch]: All log files can be found below /home/rosdev/.ros/log/2023-07-13-05-08-10-985641-f83d9cb31544-2202
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py:226> exception=InvalidLaunchFileError('py')>
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/packages.py", line 50, in get_package_prefix
    content, package_prefix = get_resource('packages', package_name)
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/resources.py", line 48, in get_resource
    raise LookupError(
LookupError: Could not find the resource 'nav2_bringup' of type 'packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 68, in get_launch_description_from_python_launch_file
    return getattr(launch_file_module, 'generate_launch_description')()
  File "/home/rosdev/colcon_ws/install/unity_slam_example/share/unity_slam_example/unity_slam_example.py", line 31, in generate_launch_description
    os.path.join(get_package_share_directory('nav2_bringup'), 'launch', 'navigation_launch.py')
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/packages.py", line 70, in get_package_share_directory
    return os.path.join(get_package_prefix(package_name), 'share', package_name)
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/packages.py", line 52, in get_package_prefix
    raise PackageNotFoundError(
ament_index_python.packages.PackageNotFoundError: "package 'nav2_bringup' not found, searching: ['/home/rosdev/colcon_ws/install/unity_slam_example', '/home/rosdev/colcon_ws/install/ros_tcp_endpoint', '/opt/ros/galactic']"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 130, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [py]: "package 'nav2_bringup' not found, searching: ['/home/rosdev/colcon_ws/install/unity_slam_example', '/home/rosdev/colcon_ws/install/ros_tcp_endpoint', '/opt/ros/galactic']"

**Comment by ccwang65** [comment]
If any one still try to fix, here is more error inside docker:

rosdev@efe8bfc4f7d3:~/colcon_ws$ rosdep install -yrq --from-paths src --ignore-src --rosdistro $ROS_DISTRO
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
unity_slam_example: Cannot locate rosdep definition for [rviz2]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully

**Comment by MetaSonGi** [comment]
![Uploading 캡처.PNG…]()
Starting the ROS node and running ros2 launch unity_slam_example unity_slam_example.py does not work.

**Comment by hansolu** [comment]
Hi... I have Same Problems...

I Followed this instructions 
https://github.com/Unity-Technologies/Robotics-Nav2-SLAM-Example/tree/main?tab=readme-ov-file

=> I got first problem with git clone, so I set ssh keys on github.

next, i got problem on   docker build -t unity-robotics:nav2-slam-example ./       ..


so i changed docker file, and change user settings..

sudo chmod 666 /var/run/docker.sock
sudo chown root:docker /var/run/docker.sock

and now i have problem in LXTerminal
https://github.com/Unity-Technologies/Robotics-Nav2-SLAM-Example/blob/main/readmes/run_example.md


I Have Ros-TCP-EndPoint folder and scripts...
--------------------------------------------- 

ros2 launch unity_slam_example unity_slam_example.py

[INFO] [launch]: All log files can be found below /home/rosdev/.ros/log/2024-01-22-14-06-25-127757-64052f25f46c-593
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py:226> exception=InvalidLaunchFileError('py')>
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/packages.py", line 50, in get_package_prefix
    content, package_prefix = get_resource('packages', package_name)
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/resources.py", line 48, in get_resource
    raise LookupError(
LookupError: Could not find the resource 'nav2_bringup' of type 'packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 68, in get_launch_description_from_python_launch_file
    return getattr(launch_file_module, 'generate_launch_description')()
  File "/home/rosdev/colcon_ws/install/unity_slam_example/share/unity_slam_example/unity_slam_example.py", line 31, in generate_launch_description
    os.path.join(get_package_share_directory('nav2_bringup'), 'launch', 'navigation_launch.py')
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/packages.py", line 70, in get_package_share_directory
    return os.path.join(get_package_prefix(package_name), 'share', package_name)
  File "/opt/ros/galactic/lib/python3.8/site-packages/ament_index_python/packages.py", line 52, in get_package_prefix
    raise PackageNotFoundError(
ament_index_python.packages.PackageNotFoundError: "package 'nav2_bringup' not found, searching: ['/home/rosdev/colcon_ws/install/unity_slam_example', '/home/rosdev/colcon_ws/install/ros_tcp_endpoint', '/opt/ros/galactic']"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 130, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [py]: "package 'nav2_bringup' not found, searching: ['/home/rosdev/colcon_ws/install/unity_slam_example', '/home/rosdev/colcon_ws/install/ros_tcp_endpoint', '/opt/ros/galactic']"
